# Generated by Django 5.0.7 on 2024-07-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_image_alter_article_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='media/th_946876594_EntghVT.jpg,th_1488217075_CVC0Ltk.jpg, th_1521804489_cfyJCMV.jpg', upload_to='articles/', verbose_name='Изображение'),
        ),
    ]
