# Generated by Django 5.0.7 on 2024-07-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scope',
            unique_together={('article', 'is_main')},
        ),
    ]
